# Generated by Django 2.1.2 on 2018-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
