# Generated by Django 2.1.2 on 2018-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermonito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRecord',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('nodename', models.CharField(max_length=32)),
                ('level', models.FloatField()),
                ('rectime', models.DateTimeField()),
            ],
        ),
    ]
